/*
This is the routing file. It was generated by the cli when we put --routing in the ng new ng6 --style=scss --routing
*/


import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

// import the components that you want to route
import { UsersComponent } from './users/users.component'
import { DetailsComponent } from './details/details.component'
import { PostsComponent } from './posts/posts.component'

const routes: Routes = [
  {
    path: '',
    component: UsersComponent
  },
  {
    path: 'details/:papi', // This is just a reference/placeholder variable named papi
    component: DetailsComponent
  },
  {
    path: 'posts',
    component: PostsComponent
  },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
